### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/thoth#14]
Currently the README implies that we still require a tls cert path, however this looks like it's outdated after the move to Postgres.

**Comment by fridex** [comment]
Are you referring to the developer's guide? https://github.com/thoth-station/thoth/blob/master/docs/developers_guide.rst

I cannot find anything TLS specific in the main README file.

Do you mind opening a PR to address that? I think the guide can point to https://github.com/thoth-station/storages/ for any additional info (all the PG related doc should be there).

**Comment by KPostOffice** [comment]
Yes sorry, the developers guide
